#!/bin/bash

MYHOME="$(pwd)"
MYSELF="vct-installer"
MYROOT="/mnt/rootfs"
MYDB="/tmp/install.db"
MYLOG="/tmp/install.log"
MYDISKDG="/tmp/disk.dg"
MYBLOCKDG="/tmp/block.dg"
MYBITE="1000"

#
# Export i18n envirnoment vairables
#
export TEXTDOMAINDIR="${MYHOME}"
export TEXTDOMAIN="${MYNAME}"

. ${MYHOME}/messages
. ${MYHOME}/common

include "dialogs"
include "database"
include "block"

{
	[ -f "${MYLOG}" ] && rm -f ${MYLOG}

	cat <<EOF
XXX
20
$(gettext 'Flush install database')
XXX
EOF
	flush_database || exit 1


	cat <<EOF
XXX
40
$(gettext 'Cleanning rootfs mountages')
XXX
EOF
	umount_all || exit 1


	cat <<EOF
XXX
60
$(gettext 'recreate database if does not exist')
XXX
EOF
	create_database || gui_die "$(gettext 'Failed to database creation')"

	cat <<EOF
XXX
90
$(gettext 'Processing block devices on system')
XXX
EOF
	search_block_devices

	cat <<EOF
XXX
100
$(gettext 'Rendering...')
XXX
EOF

	sleep 1

} | dialog "$(gettext "Loading")" --gauge "$(gettext 'loading installer. Please wait')" 10 70 0 || exit 1


#if ! check_hard_disk
#then
#	gui_die "$(gettext 'This system have not any usable hard disk')"
#fi

#if ! check_install_media
#then
#	gui_die "$(gettext 'This system have not any usable install media')"
#fi

main()
{
	log "$(gettext 'Calling main()')"

	ACTION="$(print_main_menu)"

	case $? in 
		3 )
			log_action_selected "INSTALL"
			include "install"
		;;
		0 )
			case ${ACTION} in
				1 )
					log_action_selected "1(partitioning)"
					print_disk_dg
					DISK_TO_PART=$(sh ${MYDISKDG})
					if [ "$?" == "0" ]
					then
						if [ "x${DISK_TO_PART}" != "x" ]
						then
							log_block_selected "${DISK_TO_PART}"
							open_parter ${DISK_TO_PART}
							wait
							update_partitions "${DISK_TO_PART}"
						fi
					fi
					main
				;;
				2 ) true ;;
				3 ) true ;;
				4 ) true ;;
				5 ) true ;;
				6 ) true ;;
			esac
		;;
	esac

	return 0
}
main
exit $?
